config/routes.rb
SeoMetaTags::Engine.routes.draw do

  resources :sets

  root 'sets#index'
end

app/models/seo_meta_tags/seo_set.rb
module SeoMetaTags
  class SeoSet < ActiveRecord::Base

    self.table_name = SeoMetaTags.config[:models][:table_name]

    attr_accessible :url, :title, :namespace, :description, :keywords, :images_alt

    serialize :images_alt, Hash

    validates_uniqueness_of :url, :title, :description, :keywords
    validates_length_of :title, maximum: SeoMetaTags.config[:models][:length_of_title]
    validates_length_of :description, maximum: SeoMetaTags.config[:models][:length_of_description]
    validates_length_of :keywords, maximum: SeoMetaTags.config[:models][:length_of_keywords]

    def images_alt=(images_alt_attr)
      images_alt_attr = images_alt_attr.blank? ? {} : JSON.parse(images_alt_attr)
      write_attribute(:images_alt, images_alt_attr)
    end

    def self.filter_by(params)
      @records = all
      (params || {}).select { |k, v| !v.blank? }.slice(:id, :namespace, :url, :title, :description, :keywords).each do |field, value|
        @records = @records.where("#{field} LIKE :#{field}", { field.to_sym => "%#{value}%" })
      end

      @records
    end

  end
end

app/controllers/seo_meta_tags/application_controller.rb
module SeoMetaTags
  class ApplicationController < SeoMetaTags.config[:parent_controller_class].constantize

    helper_method :page_filter

    private

    def page_filter
      return params[:filter] || {} unless SeoMetaTags.config[:store_filter_params]

      if params[:filter]
        session[:filter] = { controller_action_key => params[:filter] }
      end
      session[:filter] = { controller_action_key => { } } if params[:reset_filter] || session[:filter].nil? || session[:filter][controller_action_key].nil?

      session[:filter][controller_action_key].symbolize_keys
    end

    def controller_action_key
      controller_action_key = "#{params[:controller]}_#{params[:action]}"
    end

  end
end

app/controllers/seo_meta_tags/sets_controller.rb
require_dependency "seo_meta_tags/application_controller"

module SeoMetaTags
  class SetsController < ApplicationController

    layout SeoMetaTags.config[:layout]

    def index
      @list = SeoMetaTags::SeoSet.filter_by(page_filter).paginate(per_page: 10, page: params[:page])
    end

    def show

    end

    def new
      @seo = SeoMetaTags::SeoSet.new
    end

    def create
      @seo = SeoMetaTags::SeoSet.new(permitted_params)
      if @seo.save
        redirect_to sets_path
      else
        render :new
      end
    end

    def edit
      @seo = SeoMetaTags::SeoSet.find(params[:id])
    end

    def update
      @seo = SeoMetaTags::SeoSet.find(params[:id])
      if @seo.update_attributes(permitted_params)
        redirect_to sets_path
      else
        render :edit
      end
    end

    def destroy
      @seo = SeoMetaTags::SeoSet.find(params[:id])
      @seo.destroy
      redirect_to sets_path
    end

    private

    def permitted_params
      @permitted_params ||= params.require(:seo).permit(:url, :title, :namespace, :description, :keywords, :images_alt)
    end
  end
end

app/helpers/seo_meta_tags/application_helper.rb
module SeoMetaTags
  module ApplicationHelper
    include SeoMetaTags.config[:include_helper].constantize if SeoMetaTags.config[:include_helper]

    def method_missing method, *args, &block
      str_method_name = method.to_s
      if str_method_name.end_with?('_path') || str_method_name.end_with?('_url') && main_app.respond_to?(method)
          main_app.send(method, *args)
      else
        super
      end
    end
  end
end

app/helpers/seo_meta_tags/sets_helper.rb
module SeoMetaTags
  module SetsHelper
  end
end

app/views/layouts/seo_meta_tags/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SeoMetaTags</title>
  <%= stylesheet_link_tag    "seo_meta_tags/application", media: "all" %>
  <%= javascript_include_tag "seo_meta_tags/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/seo_meta_tags/sets/_errors.html.haml
.alert.alert-danger
  - object.errors.full_messages.each do |error|
    %p
      = error

app/views/seo_meta_tags/sets/_form.html.haml
= content_for :after_scripts do
  :javascript
    $(document).ready(function(){
    });

= form_for seo, as: :seo, url: path_to_action, html: { id: 'seo_meta'} do |f|
  .form-group.col-md-12
    - if seo.errors.any?
      = render partial: 'errors', locals: { object: seo }

  .form-group.col-md-12
    .col-md-3= f.label :title, 'Название', class: 'control-label'
    .col-md-6= f.text_area :title, rows:5

  .form-group.col-md-12
    .col-md-3= f.label :namespace, 'Поддомен(если имеется)', class: 'control-label'
    .col-md-6= f.text_field :namespace

  .form-group.col-md-12
    .col-md-3= f.label :url, 'Url', class: 'control-label'
    .col-md-6= f.text_field :url

  .form-group.col-md-12
    .col-md-3= f.label :description, 'Meta description', class: 'control-label'
    .col-md-6= f.text_area :description, rows: 5

  .form-group.col-md-12
    .col-md-3= f.label :keywords, 'Meta keywords', class: 'control-label'
    .col-md-6= f.text_area :keywords, rows: 5

  .form-group.col-md-12
    .col-md-3= f.label :images_alt, 'ALT для картинок', class: 'control-label'
    .col-md-6= f.text_area :images_alt, value: seo.images_alt.to_json, rows: 5

  .form-group
    = '*'
    %small
      Пример данных для картинок:
      %b
        =  '{"primer": "Пример"}'

  %br
  .form-group.pull-right.col-md-6
    .col-md-1
    .col-md-2= link_to 'Назад', sets_path, class: 'btn btn-default'
    .col-md-3= f.submit 'Сохранить', class: 'btn btn-success'

app/views/seo_meta_tags/sets/edit.html.haml
%h3.text-center
  Изменить СЕО элемент
%br
%br
= render partial: 'form', locals: { seo: @seo, path_to_action: set_path(@seo) }

app/views/seo_meta_tags/sets/index.html.haml
= stylesheet_link_tag "seo_meta_tags/sets"
= content_for :after_scripts do
  = javascript_include_tag 'seo_meta_tags/filter'
  :javascript
    $(document).ready(function(){
      $('#filter_row').SeoSetFilter({ $applyEl: $('#filter_apply') });
    });

%h3
  СЕО

  = link_to 'Создать', new_set_path, class: 'btn btn-success pull-right'

%br
%table.table.table-striped.table-bordered.col-md-12
  %tr#filter_row
    %td= text_field_tag 'filter[id]', page_filter[:id]
    %td= text_field_tag 'filter[namespace]', page_filter[:namespace]
    %td= text_field_tag 'filter[url]', page_filter[:url]
    %td= text_field_tag 'filter[title]', page_filter[:title]
    %td= text_field_tag 'filter[description]', page_filter[:description]
    %td= text_field_tag 'filter[keywords]', page_filter[:keywords]
    %td
    %td
      = link_to sets_path, class: 'btn btn-xs', title: 'Применить', id: 'filter_apply' do
        %i.glyphicon.glyphicon-filter

      = link_to sets_path(reset_filter: 1), class: 'btn btn-xs', title: 'Сбросить', id: 'filter_reset' do
        %i.glyphicon.glyphicon-stop

  %tr
    %th #
    %th.col-md-1 Поддомен
    %th.col-md-2 Url
    %th.col-md-1 Title
    %th.col-md-2 Meta Description
    %th.col-md-2 Meta Keywords
    %th.col.md-2 Img&nbsp;Alt
    %th.col-md-1 Действия


  - @list.each do |item|
    %tr
      %td= item.id
      %td= item.namespace
      %td= item.url
      %td= item.title
      %td= item.description
      %td= item.keywords
      %td= item.images_alt
      %td.element-actions
        = link_to edit_set_path(item), class: 'btn btn-warning btn-xs' do
          %i.glyphicon.glyphicon-pencil
        = link_to set_path(item), method: :delete, data: { confirm: 'Вы уверены?' }, class: 'btn btn-danger btn-xs' do
          %i.glyphicon.glyphicon-remove

= will_paginate @list

app/views/seo_meta_tags/sets/new.html.haml
%h3.text-center
  Новый СЕО элемент
%br
%br
= render partial: 'form', locals: { seo: @seo, path_to_action: sets_path }